package me.underlow.advent2024
import ResonantCollinearity
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day08Test {
    @Test
    fun testPart1() {
        val result = ResonantCollinearity.part1(input.split("\n"))
        assertEquals(14, result)
    }

    @Test
    fun testPart2() {
        val result = ResonantCollinearity.part2(input.split("\n"))
        assertEquals(34, result)
    }
}

private val input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
""".trimIndent()
